"""yt-dlp downloader service - full feature support."""

from __future__ import annotations

import asyncio
import logging
import os
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from fastapi import WebSocket

import yt_dlp

from api.schemas import (
    CookieStatusResponse,
    DownloadRequest,
    DownloadStatus,
    DownloadTask,
    VideoFormat,
    VideoInfoResponse,
)

logger = logging.getLogger(__name__)

DOWNLOADS_DIR = Path(os.environ.get("DOWNLOADS_DIR", "/app/downloads"))
try:
    DOWNLOADS_DIR.mkdir(parents=True, exist_ok=True)
except OSError:
    DOWNLOADS_DIR = Path("./downloads")
    DOWNLOADS_DIR.mkdir(parents=True, exist_ok=True)

COOKIES_DIR = Path(os.environ.get("COOKIES_DIR", "/app/cookies"))
try:
    COOKIES_DIR.mkdir(parents=True, exist_ok=True)
except OSError:
    COOKIES_DIR = Path("./cookies")
    COOKIES_DIR.mkdir(parents=True, exist_ok=True)

# Platforms that typically require authentication
AUTH_PLATFORMS = {
    "youtube": ["youtube.com", "youtu.be"],
    "youku": ["youku.com"],
    "tencent": ["v.qq.com", "wetv.vip"],
    "iqiyi": ["iqiyi.com"],
    "mango": ["mgtv.com"],
    "bilibili_vip": ["bilibili.com"],
    "douyin": ["douyin.com"],
}


def _normalize_url(url: str) -> str:
    """Normalize URL: add protocol, fix common issues."""
    url = url.strip()
    if not url.startswith(("http://", "https://")):
        url = "https://" + url
    if "bilibili.com" in url and "www.bilibili.com" not in url:
        url = url.replace("bilibili.com", "www.bilibili.com")

    # Douyin: convert jingxuan?modal_id=xxx or discover?modal_id=xxx to /video/xxx
    if "douyin.com" in url and "modal_id=" in url:
        import re
        match = re.search(r'modal_id=(\d+)', url)
        if match:
            video_id = match.group(1)
            url = f"https://www.douyin.com/video/{video_id}"

    # Douyin short link: v.douyin.com/xxx
    # (yt-dlp handles these natively, no change needed)

    return url


# === Copyright Compliance Filter ===

BLOCKED_PATTERNS = [
    # Paid video platforms - full episodes
    "iqiyi.com/v_",
    "youku.com/v_show",
    "mgtv.com/b/",
    # International streaming
    "netflix.com",
    "disneyplus.com",
    "hbomax.com",
    "hulu.com",
    "primevideo.com",
    "peacocktv.com",
    "paramountplus.com",
    "crunchyroll.com/watch",
]

BLOCKED_KEYWORDS_IN_TITLE = ["会员专享", "VIP专属", "付费观看", "独播", "会员抢先"]


def _check_copyright_compliance(url: str) -> Optional[str]:
    """Check if URL targets copyrighted content. Returns error message or None."""
    url_lower = url.lower()
    for pattern in BLOCKED_PATTERNS:
        if pattern.lower() in url_lower:
            return (
                "为保护版权，本工具不支持下载该平台的影视剧/付费内容。"
                "本工具仅支持下载用户自有版权或公开授权的内容。"
                "如需备份您的原创作品，请使用对应平台的官方创作者工具导出。"
            )
    return None


def _detect_platform(url: str) -> Optional[str]:
    """Detect which platform a URL belongs to."""
    for platform, domains in AUTH_PLATFORMS.items():
        for domain in domains:
            if domain in url:
                return platform
    return None


class DownloaderService:
    """Service class wrapping yt-dlp full functionality."""

    def __init__(self) -> None:
        self._tasks: dict[str, DownloadTask] = {}
        self._websockets: dict[str, WebSocket] = {}
        self._active_loops: dict[str, asyncio.AbstractEventLoop] = {}

    def get_downloads_dir(self) -> Path:
        return DOWNLOADS_DIR

    # === Cookie Management ===

    def save_cookies(self, platform: str, cookies_text: str) -> None:
        """Save cookies for a platform in Netscape format."""
        if not cookies_text.strip():
            raise ValueError("Cookies 内容不能为空")
        cookie_file = COOKIES_DIR / f"{platform}.txt"
        # Ensure Netscape header
        content = cookies_text.strip()
        if not content.startswith("# Netscape HTTP Cookie File"):
            content = "# Netscape HTTP Cookie File\n# This file is generated by SnapVid\n\n" + content
        cookie_file.write_text(content, encoding="utf-8")

    def get_cookies_status(self) -> list[CookieStatusResponse]:
        """Get status of saved cookies for all platforms."""
        results = []
        for platform in AUTH_PLATFORMS:
            cookie_file = COOKIES_DIR / f"{platform}.txt"
            has_cookies = cookie_file.exists() and cookie_file.stat().st_size > 50
            results.append(CookieStatusResponse(
                platform=platform,
                has_cookies=has_cookies,
                expires_hint="已配置" if has_cookies else "未配置",
            ))
        return results

    def delete_cookies(self, platform: str) -> None:
        """Delete cookies for a platform."""
        cookie_file = COOKIES_DIR / f"{platform}.txt"
        if cookie_file.exists():
            cookie_file.unlink()

    def _get_cookie_file(self, url: str) -> Optional[str]:
        """Get cookie file path if available for this URL's platform."""
        platform = _detect_platform(url)
        if platform:
            cookie_file = COOKIES_DIR / f"{platform}.txt"
            if cookie_file.exists():
                return str(cookie_file)
        return None

    # === Video Info ===

    async def get_video_info(self, url: str, platform_cookie: Optional[str] = None) -> VideoInfoResponse:
        """Extract video information from URL with full yt-dlp features."""
        if not url or not url.strip():
            raise ValueError("URL不能为空")

        url = _normalize_url(url)

        # Copyright compliance check
        block_msg = _check_copyright_compliance(url)
        if block_msg:
            raise ValueError(block_msg)

        url = _normalize_url(url)

        ydl_opts: dict = {
            "quiet": True,
            "no_warnings": True,
            "extract_flat": False,
            "skip_download": True,
            "http_headers": {
                "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
                "Referer": url,
            },
            "extractor_args": {
                "BiliBili": {"lang": ["zh-Hans"]},
                "youtube": {"player_client": ["web"]},
            },
            "socket_timeout": 15,
        }

        # Note: impersonate requires curl_cffi with specific version compatibility
        # Currently disabled - rely on cookies + headers instead

        # Apply cookies if available
        cookie_file = self._get_cookie_file(url)
        if cookie_file:
            ydl_opts["cookiefile"] = cookie_file

        loop = asyncio.get_event_loop()
        info = await loop.run_in_executor(None, self._extract_info, url, ydl_opts)

        if info is None:
            raise ValueError("无法获取视频信息，请检查URL是否正确")

        # Detect if auth is required
        platform = _detect_platform(url)
        requires_auth = platform is not None and not self._get_cookie_file(url)

        # Parse formats
        formats: list[VideoFormat] = []
        raw_formats = info.get("formats", [])
        for fmt in raw_formats:
            vcodec = fmt.get("vcodec", "none") or "none"
            acodec = fmt.get("acodec", "none") or "none"
            resolution = fmt.get("resolution", "audio only" if vcodec == "none" else "")
            if not resolution:
                width = fmt.get("width", 0) or 0
                height = fmt.get("height", 0) or 0
                if width and height:
                    resolution = f"{width}x{height}"
                else:
                    resolution = "unknown"

            formats.append(VideoFormat(
                format_id=fmt.get("format_id", ""),
                format_note=fmt.get("format_note", ""),
                ext=fmt.get("ext", ""),
                resolution=resolution,
                filesize=fmt.get("filesize") or fmt.get("filesize_approx"),
                vcodec=vcodec,
                acodec=acodec,
                tbr=fmt.get("tbr"),
            ))

        # Parse subtitles
        subtitles: list[str] = list(info.get("subtitles", {}).keys())
        auto_subs = list(info.get("automatic_captions", {}).keys())
        all_subs = list(set(subtitles + auto_subs))

        # Parse chapters
        chapters = info.get("chapters")

        # Duration
        duration = info.get("duration")
        duration_string = ""
        if duration:
            hours = int(duration) // 3600
            minutes = (int(duration) % 3600) // 60
            seconds = int(duration) % 60
            if hours > 0:
                duration_string = f"{hours:02d}:{minutes:02d}:{seconds:02d}"
            else:
                duration_string = f"{minutes:02d}:{seconds:02d}"

        return VideoInfoResponse(
            title=info.get("title", "未知标题"),
            duration=duration,
            duration_string=duration_string,
            thumbnail=info.get("thumbnail", ""),
            uploader=info.get("uploader", info.get("channel", "未知")),
            platform=info.get("extractor_key", info.get("extractor", "未知平台")),
            description=info.get("description", "") or "",
            formats=formats,
            subtitles=all_subs,
            chapters=chapters,
            requires_auth=requires_auth,
        )

    def _extract_info(self, url: str, ydl_opts: dict) -> Optional[dict]:
        """Extract info using yt-dlp (synchronous)."""
        try:
            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                return ydl.extract_info(url, download=False)
        except yt_dlp.utils.DownloadError as e:
            err_msg = str(e)
            if "Sign in to confirm" in err_msg or "bot" in err_msg:
                raise ValueError(
                    "该平台要求登录验证。请在「账号管理」中导入对应平台的 Cookies 后重试。"
                )
            elif "Fresh cookies" in err_msg or "cookies" in err_msg.lower():
                raise ValueError(
                    "抖音需要包含 ttwid/msToken 的完整 Cookies（需通过浏览器扩展「Get cookies.txt LOCALLY」导出，"
                    "不能用书签脚本方式）。请使用方法二：安装 Chrome 扩展后，在抖音网页上导出完整 Cookies。"
                )
            elif "Video unavailable" in err_msg:
                raise ValueError("视频不可用：可能是地区限制、需要会员或视频已被删除")
            elif "HTTP Error 403" in err_msg:
                raise ValueError("访问被拒绝 (403)：请导入该平台的 Cookies 或稍后重试")
            elif "Unsupported URL" in err_msg:
                raise ValueError("不支持的链接格式，请复制视频的完整分享链接（而非页面URL）")
            raise ValueError(f"视频解析失败: {err_msg}")
        except Exception as e:
            raise ValueError(f"视频解析出错: {str(e)}")

    # === Download ===

    async def start_download(self, request: DownloadRequest) -> str:
        """Start a download task with full feature support."""
        if not request.url or not request.url.strip():
            raise ValueError("URL不能为空")

        request.url = _normalize_url(request.url)

        task_id = str(uuid.uuid4())
        now = datetime.now(timezone.utc).isoformat()

        task = DownloadTask(
            id=task_id,
            url=request.url,
            title="获取中...",
            status=DownloadStatus.PENDING,
            progress=0.0,
            speed="",
            eta="",
            filename="",
            filesize=None,
            error="",
            created_at=now,
        )
        self._tasks[task_id] = task
        asyncio.create_task(self._run_download(task_id, request))
        return task_id

    async def _run_download(self, task_id: str, request: DownloadRequest) -> None:
        """Run the download task with all yt-dlp features."""
        task = self._tasks.get(task_id)
        if task is None:
            return

        task.status = DownloadStatus.DOWNLOADING
        loop = asyncio.get_event_loop()
        self._active_loops[task_id] = loop

        # Build yt-dlp options
        output_template = str(DOWNLOADS_DIR / f"{task_id}_%(title)s.%(ext)s")
        ydl_opts: dict = {
            "outtmpl": output_template,
            "quiet": True,
            "no_warnings": True,
            "progress_hooks": [lambda d: self._sync_progress_hook(task_id, d)],
            "http_headers": {
                "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36",
                "Referer": request.url,
            },
        }

        # Apply cookies
        cookie_file = self._get_cookie_file(request.url)
        if cookie_file:
            ydl_opts["cookiefile"] = cookie_file

        # Format selection
        if request.audio_only:
            ydl_opts["format"] = "bestaudio/best"
            ydl_opts["postprocessors"] = [{
                "key": "FFmpegExtractAudio",
                "preferredcodec": request.audio_format,
                "preferredquality": request.audio_quality,
            }]
        elif request.format_id and request.format_id != "best":
            ydl_opts["format"] = f"{request.format_id}+bestaudio/best"
        else:
            ydl_opts["format"] = "bestvideo+bestaudio/best"

        # Output container
        if not request.audio_only and request.output_format:
            ydl_opts["merge_output_format"] = request.output_format

        # Subtitles
        if request.subtitles:
            ydl_opts["writesubtitles"] = True
            ydl_opts["subtitleslangs"] = [request.subtitles]
            if request.embed_subtitles:
                ydl_opts.setdefault("postprocessors", []).append({
                    "key": "FFmpegEmbedSubtitle",
                })

        # Playlist
        if not request.playlist:
            ydl_opts["noplaylist"] = True
        elif request.playlist_range:
            ydl_opts["playlist_items"] = request.playlist_range

        # Rate limit
        if request.rate_limit and request.rate_limit > 0:
            ydl_opts["ratelimit"] = int(request.rate_limit * 1024 * 1024)

        # Embed thumbnail
        if request.embed_thumbnail:
            ydl_opts["writethumbnail"] = True
            ydl_opts.setdefault("postprocessors", []).append({
                "key": "EmbedThumbnail",
            })

        # Embed metadata
        if request.embed_metadata:
            ydl_opts.setdefault("postprocessors", []).append({
                "key": "FFmpegMetadata",
            })

        # Split by chapters
        if request.split_chapters:
            ydl_opts.setdefault("postprocessors", []).append({
                "key": "FFmpegSplitChapters",
            })

        # SponsorBlock (YouTube)
        if request.sponsor_block:
            ydl_opts.setdefault("postprocessors", []).append({
                "key": "SponsorBlock",
            })
            ydl_opts.setdefault("postprocessors", []).append({
                "key": "ModifyChapters",
                "remove_sponsor_segments": ["sponsor", "selfpromo", "interaction"],
            })

        # Proxy
        if request.proxy:
            ydl_opts["proxy"] = request.proxy

        # === New features ===

        # Multi-thread concurrent fragments (Pro feature)
        if request.concurrent_fragments and request.concurrent_fragments > 1:
            ydl_opts["concurrent_fragment_downloads"] = min(request.concurrent_fragments, 16)

        # Download specific time section
        if request.download_sections:
            ydl_opts["download_ranges"] = lambda info, ydl: [
                {"start_time": self._parse_time(request.download_sections.split("-")[0]),
                 "end_time": self._parse_time(request.download_sections.split("-")[1])}
            ] if "-" in request.download_sections else []
            # Use simpler approach via postprocessor
            ydl_opts["postprocessor_args"] = {"ffmpeg": []}
            # Actually use download_sections format
            ydl_opts.pop("download_ranges", None)
            ydl_opts["download_ranges"] = None
            # yt-dlp native section support
            if "-" in request.download_sections:
                parts = request.download_sections.split("-")
                ydl_opts["postprocessor_args"] = {
                    "ffmpeg": ["-ss", parts[0].strip(), "-to", parts[1].strip()]
                }
                ydl_opts["force_keyframes_at_cuts"] = True

        # Custom filename template
        if request.output_template:
            safe_template = request.output_template.replace("/", "_").replace("\\", "_")
            output_template = str(DOWNLOADS_DIR / f"{task_id}_{safe_template}.%(ext)s")
            ydl_opts["outtmpl"] = output_template

        # Thumbnail only download
        if request.thumbnail_only:
            ydl_opts["skip_download"] = True
            ydl_opts["writethumbnail"] = True
            ydl_opts["postprocessors"] = [{
                "key": "FFmpegThumbnailsConvertor",
                "format": "png",
            }]

        # Remux (format conversion without re-encoding)
        if request.remux_format and not request.audio_only:
            ydl_opts.setdefault("postprocessors", []).append({
                "key": "FFmpegVideoRemuxer",
                "preferedformat": request.remux_format,
            })

        try:
            downloaded_file = await loop.run_in_executor(
                None, self._do_download, request.url, ydl_opts, task_id
            )
            task.status = DownloadStatus.COMPLETED
            task.progress = 100.0
            if downloaded_file:
                task.filename = Path(downloaded_file).name
                try:
                    task.filesize = Path(downloaded_file).stat().st_size
                except OSError:
                    pass
            await self._send_progress(task_id, {
                "progress": 100.0,
                "speed": "",
                "eta": "00:00",
                "status": "completed",
            })
        except Exception as e:
            logger.error(f"Download failed for task {task_id}: {e}")
            task.status = DownloadStatus.FAILED
            task.error = str(e)
            await self._send_progress(task_id, {
                "progress": task.progress,
                "speed": "",
                "eta": "",
                "status": "failed",
                "error": str(e),
            })
        finally:
            self._active_loops.pop(task_id, None)

    def _do_download(self, url: str, ydl_opts: dict, task_id: str) -> Optional[str]:
        """Execute the actual download."""
        try:
            with yt_dlp.YoutubeDL(ydl_opts) as ydl:
                info = ydl.extract_info(url, download=True)
                if info:
                    task = self._tasks.get(task_id)
                    if task:
                        task.title = info.get("title", "未知标题")

                    filename = ydl.prepare_filename(info)
                    # Handle audio postprocessing extension change
                    if ydl_opts.get("postprocessors"):
                        for pp in ydl_opts["postprocessors"]:
                            if pp.get("key") == "FFmpegExtractAudio":
                                codec = pp.get("preferredcodec", "mp3")
                                base = Path(filename).stem
                                audio_path = Path(filename).parent / f"{base}.{codec}"
                                if audio_path.exists():
                                    return str(audio_path)
                    if Path(filename).exists():
                        return filename
                    # Try common extensions
                    base = Path(filename).with_suffix("")
                    for ext in [".mp4", ".webm", ".mkv", ".mp3", ".m4a", ".flac", ".wav", ".opus"]:
                        candidate = Path(str(base) + ext)
                        if candidate.exists():
                            return str(candidate)
                return None
        except yt_dlp.utils.DownloadError as e:
            raise RuntimeError(f"下载失败: {str(e)}")
        except Exception as e:
            raise RuntimeError(f"下载出错: {str(e)}")

    def _sync_progress_hook(self, task_id: str, data: dict) -> None:
        """Synchronous progress hook called by yt-dlp."""
        task = self._tasks.get(task_id)
        if task is None:
            return

        status = data.get("status", "")
        if status == "downloading":
            total = data.get("total_bytes") or data.get("total_bytes_estimate") or 0
            downloaded = data.get("downloaded_bytes", 0)
            if total > 0:
                task.progress = round((downloaded / total) * 100, 1)

            speed = data.get("speed")
            if speed and speed > 0:
                if speed > 1024 * 1024:
                    task.speed = f"{speed / (1024 * 1024):.1f}MB/s"
                elif speed > 1024:
                    task.speed = f"{speed / 1024:.1f}KB/s"
                else:
                    task.speed = f"{speed:.0f}B/s"
            else:
                task.speed = ""

            eta = data.get("eta")
            if eta and eta > 0:
                minutes = int(eta) // 60
                seconds = int(eta) % 60
                task.eta = f"{minutes:02d}:{seconds:02d}"
            else:
                task.eta = ""

            loop = self._active_loops.get(task_id)
            if loop and self._websockets.get(task_id):
                asyncio.run_coroutine_threadsafe(
                    self._send_progress(task_id, {
                        "progress": task.progress,
                        "speed": task.speed,
                        "eta": task.eta,
                        "status": "downloading",
                    }),
                    loop,
                )

        elif status == "finished":
            task.progress = 99.0
            task.speed = ""
            task.eta = "处理中..."

    async def _send_progress(self, task_id: str, data: dict) -> None:
        """Send progress data via WebSocket."""
        ws = self._websockets.get(task_id)
        if ws:
            try:
                await ws.send_json(data)
            except Exception:
                self._websockets.pop(task_id, None)

    async def subscribe_progress(self, websocket: WebSocket, task_id: str) -> None:
        """Subscribe to progress updates via WebSocket."""
        self._websockets[task_id] = websocket

        task = self._tasks.get(task_id)
        if task:
            await websocket.send_json({
                "progress": task.progress,
                "speed": task.speed,
                "eta": task.eta,
                "status": task.status.value,
            })

        try:
            while True:
                # Keep alive: longer timeout, loop until task finishes
                try:
                    await asyncio.wait_for(websocket.receive_text(), timeout=60.0)
                except asyncio.TimeoutError:
                    # Check if task is done
                    task = self._tasks.get(task_id)
                    if task and task.status in (DownloadStatus.COMPLETED, DownloadStatus.FAILED):
                        # Send final status before closing
                        await websocket.send_json({
                            "progress": task.progress,
                            "speed": "",
                            "eta": "",
                            "status": task.status.value,
                        })
                        return
                    # Otherwise keep connection alive by sending current progress
                    if task:
                        await websocket.send_json({
                            "progress": task.progress,
                            "speed": task.speed,
                            "eta": task.eta,
                            "status": task.status.value,
                        })
        except Exception:
            pass

    def unsubscribe_progress(self, task_id: str) -> None:
        self._websockets.pop(task_id, None)

    @staticmethod
    def _parse_time(time_str: str) -> float:
        """Parse time string like '01:30' or '1:02:30' to seconds."""
        time_str = time_str.strip()
        parts = time_str.split(":")
        if len(parts) == 3:
            return int(parts[0]) * 3600 + int(parts[1]) * 60 + float(parts[2])
        elif len(parts) == 2:
            return int(parts[0]) * 60 + float(parts[1])
        return float(time_str)

    def get_all_tasks(self) -> list[DownloadTask]:
        tasks = list(self._tasks.values())
        tasks.sort(key=lambda t: t.created_at, reverse=True)
        return tasks

    def get_task(self, task_id: str) -> Optional[DownloadTask]:
        return self._tasks.get(task_id)

    def delete_task(self, task_id: str) -> bool:
        task = self._tasks.get(task_id)
        if task is None:
            return False
        if task.filename:
            file_path = DOWNLOADS_DIR / task.filename
            if file_path.exists():
                try:
                    file_path.unlink()
                except OSError as e:
                    logger.warning(f"Failed to delete file {file_path}: {e}")
        del self._tasks[task_id]
        return True
