// SnapVid Cookie Helper - Background Service Worker
// Listens for messages from popup and extracts cookies for target platforms

const SNAPVID_SERVER = 'http://localhost:9090';

const PLATFORM_DOMAINS = {
  douyin: ['.douyin.com'],
  youtube: ['.youtube.com'],
  bilibili: ['.bilibili.com'],
  youku: ['.youku.com'],
  tencent: ['.qq.com'],
  iqiyi: ['.iqiyi.com'],
  mango: ['.mgtv.com'],
};

// Convert Chrome cookies to Netscape format
function toNetscape(cookies, domain) {
  let lines = ['# Netscape HTTP Cookie File', '# Generated by SnapVid Cookie Helper', ''];
  for (const c of cookies) {
    const secure = c.secure ? 'TRUE' : 'FALSE';
    const httpOnly = c.httpOnly ? 'TRUE' : 'FALSE';
    const expires = c.expirationDate ? Math.floor(c.expirationDate) : 0;
    const d = c.domain.startsWith('.') ? c.domain : '.' + c.domain;
    lines.push(`${d}\tTRUE\t${c.path}\t${secure}\t${expires}\t${c.name}\t${c.value}`);
  }
  return lines.join('\n');
}

// Extract cookies for a platform and send to SnapVid
async function extractAndSend(platformId) {
  const domains = PLATFORM_DOMAINS[platformId];
  if (!domains) return { success: false, error: 'Unknown platform' };

  let allCookies = [];
  for (const domain of domains) {
    const cookies = await chrome.cookies.getAll({ domain });
    allCookies = allCookies.concat(cookies);
  }

  if (allCookies.length === 0) {
    return { success: false, error: '未找到该平台的 Cookies，请先在浏览器中访问该平台' };
  }

  const netscape = toNetscape(allCookies, domains[0]);

  try {
    const resp = await fetch(`${SNAPVID_SERVER}/api/cookies`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ platform: platformId, cookies_text: netscape }),
    });
    if (resp.ok) {
      return { success: true, count: allCookies.length };
    } else {
      const err = await resp.json();
      return { success: false, error: err.detail || '上传失败' };
    }
  } catch (e) {
    return { success: false, error: `无法连接 SnapVid (${SNAPVID_SERVER})` };
  }
}

// Listen for messages from popup
chrome.runtime.onMessage.addListener((msg, sender, sendResponse) => {
  if (msg.action === 'extract') {
    extractAndSend(msg.platform).then(sendResponse);
    return true; // async response
  }
  if (msg.action === 'extractAll') {
    (async () => {
      const results = {};
      for (const pid of Object.keys(PLATFORM_DOMAINS)) {
        results[pid] = await extractAndSend(pid);
      }
      sendResponse(results);
    })();
    return true;
  }
});
